---
title: "Butter and Butter Substitutes"
description: |
  What types of butter we typically use, and how we substitute different
  things in depending on the recipe.
author:
  - name: Robert M Flight
    url: {}
date: 2022-08-07
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

## Butter

If you look at the recipes on this site, you will notice that a bunch of them use
butter, or butter substitutes (technically margarine).

## Unsalted vs Salted

I know most baking recommends using unsalted butter, and then add specific amount of
salt to the recipe for flavor enhancement.

Historically, our family doesn't add very much salt to their food, so we find that 
adding any amount of salt, especially baked goods, makes them much too salty.

Therefore, in our baking, we typically use salted butter, or a butter substitute
that contains salt, and then don't add any extra salt to the recipe.

## Butter Substitutes

We have one child who is rather severely lactose intolerant, as in they can't consume
regular milk, yogurt or cheese.
Even the brand of lactose free milk can make a difference, as it seems some are
better at adding enough lactase enzyme over others. 
Pro-tip, Lactaid brand seems fine, as does the Aldi and Walmart brand lactose free milks.
Kroger brand is **not** fine, at least in our family.

Therefore, we use plant based butter substitutes in **almost** all of our recipes, 
unless the recipe also includes cheese, in which case we don't bother.

However, depending on what exactly is being cooked, in my experience it seems that 
different butter substitutes are more appropriate, factoring in taste, extra water added, etc.

I shop at our local WalMart, so this is all based on what I can buy there.

* [Great Value Unsalted Butter](https://www.walmart.com/ip/Great-Value-Unsalted-Sweet-Cream-Butter-16-oz-4-Sticks/10315054?athbdg=L1100): goes in my coffee (yes, I like butter in my coffee), and 
also used in the cheese sauce for my [Mac & Cheese](https://rmflight.github.io/recipes/posts/2021-03-20-mac-cheese/).
* [Country Crock Plant Butter](https://www.walmart.com/ip/Country-Crock-Dairy-Free-Plant-Butter-with-Olive-Oil-Sticks-16-oz/409121348?athbdg=L1100): In cookies, cakes and muffins, this is a straight substitute.
However, this does not work for buttercream icing, roux, or bread dough based recipes like cinnamon buns.
In the case of a roux, the butter taste is **too** strong.
Buttercream icing ends up with a weird consistency.
Bread dough doesn't seem to rise properly.
* [Smart Balance Buttery Spread](https://www.walmart.com/ip/Smart-Balance-Original-Buttery-Spread-45-OZ/10411892): This one I use when I'm making a dairy free or lactose free roux, like for our Chicken Pot Pie, and we also use in bread doughs and buttercream icing.
