---
title: "Poached Chicken Breast (Instant Pot)"
description: |
  Poached chicken breast that shreds nicely for other recipes.
author:
  - name: Robert M Flight
    url: {}
date: 2021-11-06
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories:
  - chicken
  - instant-pot
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Ingredients

* 5 tsp salt (or just a couple, really)
* 2 bay leaves
* 1 tsp dried thyme
* 1 tsp rosemary
* 1 tsp oregano
* 4 cups water
* 2 chicken breasts

## Directions

* Add dried herbs to instant pot insert.
* Add **4 cups** water.
* Add 2 chicken breasts (either whole or in chunks).

* Set timer for 0 (yes, really) minutes, or if not possible, 1 minute.
* When pressure is reached, if you had to set 1 minute, get up and turn the instant pot off.
* Hit "keep warm" to at least keep it warm but naturally release
* For 
  * 1 chicken breast - 12 min
  * 2 chicken breasts - 11 min
  * 4 chicken breasts - 9 min
* Release pressure.
* Check temperature with a meat thermometer.
Supposedly 165F is safe, but I still prefer 180F.

## Frozen

* For frozen chicken breasts:
  * 2 chicken breasts - 3 minutes at pressure, 18 - 20 minute rest.

## Wait, why?

As far as I can understand, we are using the heat necessary to get the mass of water + chicken to a boiling point to actually cook the chicken (poaching).
This means that the more *cold* chicken breast you put in, the more heat it will take to get it to pressure, and therefore you need *less* time to naturally release.
However, we are talking changes of 1 - 2 minutes, in salty water.

I use this to make shredded chicken breast for soup, chicken pot pie, etc.

Original guidelines are from [Amy & Jacky Pressure Cook Recipes](https://www.pressurecookrecipes.com/instant-pot-chicken-breast/).
