project:
  type: website
  output-dir: docs

website:
  title: "Flight Family Recipes"
  site-url: "https://rmflight.github.io/recipes"
  navbar:
    right:
      - text: Home
        href: index.html
      - text: Old Recipes
        href: https://github.com/rmflight/recipes/tree/main/old_recipes
      - text: Welcome
        href: posts/welcome/index.html
      - icon: github
        href: https://github.com/rmflight/recipes
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      dark: darkly
      light: flatly

