---
title: "Chicken Soup"
description: |
  This chicken soup is yummy, and you know exactly what's in it.
author:
  - name: Robert M Flight
    url: {}
date: 2021-11-07
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories:
  - soup
  - chicken
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Ingredients

* 2 tbsp butter
* 2 cups diced carrots
* 1 tbsp minced onion
* 2 garlic cloves (or 2 tsp minced garlic)
* 8 cups vegetable broth (two 32 oz boxes)
* 1/2 tsp dried basil
* 1/2 tsp dried oregano
* dash of sage
* salt and pepper to taste
* 3 cups egg noodles
* 2 cups cooked and shredded chicken breasts ([see here](https://rmflight.github.io/recipes/posts/2021-11-06-poached-chicken-breast-instant-pot/))

## Directions

* In large pot over medium heat, melt **2 tbsp** butter.
* Cook **1/2 minced** onion and **2 cups** diced carrot in butter until tender (~ 5 min).
* Add garlic and cook an additional minute.
* Pour in vegetable broth and stir in **3 cups** egg noodles; **1/2 tsp** oregano, **1/2 tsp** basil, dash of sage, salt and pepper.
* Check the taste now and add any more seasoning you think it needs.
* Stir in **2 cups** shredded chicken (putting it in now means the chicken flavor will well permeate the soup, a plus if you are using vegetable broth, if using chicken broth, add it after simmering).
* Bring to a boil, reduce heat and simmer 15 - 20 minutes.

From [The Girl Who Ate Everything](https://www.the-girl-who-ate-everything.com/homemade-chicken-noodle-soup/).

## Notes:

Yes, I use vegetable broth.
My digestive system does not seem to do well with the dried broth when you add enough powder to make it taste chickeny enough, and the same for "Better than Boullion".
If you really want chicken broth, go for it.
In my experience, the vegetable broth tasted great, **especially** if you add the chicken before letting it simmer.
