---
title: "Balsamic Chicken & Mushrooms"
description: |
  Tangy, flavor bombs of mushroom and chicken in Balsamic sauce.
author:
  - name: Robert M Flight
    url: {}
date: 04-11-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories: 
  - meat
  - chicken
  - mushrooms
  - main-dish
---

## Ingredients

* 4 Tbsp Balsamic vinegar
* 1.5 Tbsp soy sauce
* 1 Tbsp brown sugar
* 2 cloves garlic, minced
* 1/4 tsp dried thyme
* 1 1/4 lbs boneless, skinless chicken breast cut into small pieces
* 1 pinch salt and pepper
* 1 Tbsp olive oil
* 16 oz or 1 lb white mushrooms
* 2 Tbsp butter

## Directions

* Prepare the balsamic sauce first. 
* In a small bowl, stir together **4 Tbsp** balsamic vinegar, **1.5 Tbsp** soy sauce, **1 Tbsp** brown sugar, **2 cloves** (or 2 tsp) minced garlic, and **1/4 tsp** dried thyme. 
* Set the sauce aside.

* Heat a large skillet over medium. 
* Once hot, add the olive oil and swirl to coat the surface. 
* Add the pieces of chicken breast to the skillet and cook browned and cooked through. 
* Remove the chicken to a clean plate and cover to keep warm.

* While the chicken is cooking, clean **16 oz** of mushrooms and then slice the bigger ones in half. 
* After removing the chicken from the skillet, add the mushrooms in their place, and sauté in the remaining oil and fat until the mushrooms are slightly tender and browned on the outside (5-7 minutes).

* Turn the heat down to medium-low. 
* Add the prepared balsamic sauce to the skillet and stir to dissolve any browned bits from the bottom of the skillet. 
* Add chicken back to the skillet.
* Allow the sauce to come up to a simmer. 
* Simmer the balsamic sauce with the chicken & mushrooms, stirring occasionally, for about 5 minutes, or until the sauce has reduced by half.
* Add the butter to the skillet and stir until it is melted into the sauce. 

Originally from https://www.budgetbytes.com/balsamic-chicken-and-mushrooms/
