---
title: "Crosby's Baked Beans"
description: |
  Instant-Pot makes these molasses baked beans a snap.
categories:
  - instant-pot
  - beans
  - molasses
  - soup
date: 03-07-2021
---

## Ingredients

* 2 cups dried navy or pea beans
* 1 small onion, peeled
* One small apple, peeled and cored
* 1/3 cup brown sugar
* 1 cup molasses (1/2 cup is not enough in my opinion)
* 1 tsp. salt
* 1 1/2 tsp. dried mustard
* 1/2 Tbsp. Worcestershire sauce
* 1/2 tsp. freshly ground black pepper
* 2 cups boiling water

## Directions

* Place **2 cups** dried beans in the instant pot and cover with an inch of water (about 4 cups).
* Secure the lid, turn the pot’s steam vent to close. On manual mode, set the timer for 20 minutes.
* While the beans are cooking, combine **1/3 cup** brown sugar, **1/2 cup** molasses, **1 tsp** salt, **1 1/2 tsp** dried mustard, **1/2 Tbsp** Worcestershire, and **1/2 tsp** black pepper in a bowl.
* Add two cups of boiling water and stir to combine.

* When the timer beeps, allow the pot to depressurize for about 20 minutes, press “cancel” and then carefully turn the steam vent to open and remove the lid.
* Drain the beans well and return them to the pot.

* Bury **1 small** onion and **1** apple in the beans and pour molasses mixture over the beans.
* Secure the lid, turn the steam vent to close, and set the timer for 16 minutes.
* When the 16 minutes are up (timer beeps), allow your pot to depressurize another 20 minutes, turn steam vent to open and remove lid.
* If your beans are too runny, turn unit to saute mode and saute for 5-7 minutes, stirring from time to time.

From Crosby's site: https://www.crosbys.com/instant-pot-molasses-baked-beans/
