---
title: "Pork & Apples (Instant Pot)"
description: |
  Delicious pork chops in a sweet apple gravy.
date: 04-11-2021
categories:
  - instant-pot
  - pork
  - meat
  - main-dish
---

## Ingredients

* 3 Apples sliced about 1/4" thick
* 1 Small Sweet Onion (Walla Walla, Vidalia, etc) cut in half and thinly sliced.
* 2-4 Pork Chops 
* Salt
* Pepper
* 1 Tbsp Vegetable Oil
* 1/4 cup Plus 1 Tbsp Water (divided)
* 4 Tbsp Butter (unsalted)
* 4 Tbsp Brown Sugar
* 1/4 tsp Cinnamon
* 1/4 tsp Nutmeg
* Pinch of Salt
* 2 Tbsp Corn Starch
* 3 Tbsp Cold Water

## Directions

* Prepare **3** apples by peeling, coring, and slicing. Set aside.
* Remove the outer skin of **1 small sweet** onion. Cut in half and slice thinly (You will have half circles). Set aside.
* Season **2 - 4** pork chops with a sprinkling of salt and pepper on each side. Go lightly on the pepper. Set aside while pot warms up.
* Turn the IP to Sauté mode (Normal heat). When the display reads "Hot" add **1 Tbsp** oil to the pot.
* Add the pork chops, two at a time, and brown on each side for about 4 minutes per side (less if thin). Remove to a plate and set aside.
* Add the onion and **1 Tbsp** water. Cook the onion, stirring frequently and scraping to deglaze the pot (get all of the brown bits off the bottom). I like to use a wooden spoon.
* When the onions are translucent and tender, add the **4 Tbsp** butter and stir until melted.
* Add the apples and **1/4 cup** water. Stir well.
* Add the pork chops (and any juices on the plate) back in and just set them on top of the apples. Don't stir. 
* Put the lid on the pot and set the steam release knob to the Sealing position. Cancel the Sauté mode.
* Press the Manual (or Pressure Cook) button and then the + or - button to select 10 (8 minutes for thinner chops) minutes.

Yes, the pot will come to pressure with only 1/4 cup of water in it. This is because the apples will release water as the pot is heating up and building pressure, so you will be okay. It's the same for making applesauce!

* While the pork chops are cooking, mix together the **4 Tbsp** brown sugar, **1/4 tsp** cinnamon, **1/4 tsp** nutmeg, and a pinch of salt. Set aside.
* When the cook cycle ends and the pot beeps, don't do anything to it, just let it naturally release pressure for 10 minutes (the counter will begin counting up). 
* After the 10 minutes is up, turn the steam release knob to manually release the remaining pressure.
When the pin in the lid drops, open the lid. Remove the pork chops to a plate and cover with foil or a lid to keep warm.

* Turn the Sauté mode back on.
* Add the brown sugar mixture to the apple mixture and stir.
* Mix the **2 Tbsp** corn starch with **3 Tbsp** cold water. Stir the corn starch slurry into the apple mixture, stirring constantly.
* When the mixture thickens, turn off the pot. Remove apple gravy to a serving bowl immediately.
* Serve the pork chops smothered in the warm apple gravy. Yum!

From https://www.simplyhappyfoodie.com/instant-pot-autumn-apple-pork-chops/
