---
title: "Breakfast Cookies"
subtitle: |
  A different way to enjoy cereal ...
date: 2025-01-14
categories: [breakfast, cookie, cookies]
editor_options:
  chunk_output_type: console
---

## Ingredients

* 2 cups white sugar
* 1 1/3 cups creamy peanut butter
* 1 cup butter, softened
* 2 Tbsp vaniall
* 2 eggs, lightly beaten
* 2 1/4 cups flour
* 1 tsp baking soda
* 1 1/2 cups instant oats
* 1 1/2 cups raisins
* 4 1/2 cups toasted oat cereal (i.e. Cheerios)

## Directions

* Preheat oven to 375F.
* In a large bowl, mix together **2 cups white sugar**, **1 1/3 cups** peanut butter, **1 cup** softened butter, **2 Tbsp** vanilla, **2 eggs** on medium until smooth.
* Another bowl, stir together **2 1/4 cups** flour, **1 tsp** baking soda.
* Mix flour mixture into peanut butter mixture at low speed until just combined.
* Mix in **1 1/2 cups** raisins and **1 1/2 cups** instant oats.
* Finally, with a spatula (or your hands), mix in **4 1/2 cups** toasted oat cereal.
* Drop **1/2 cup** portions onto a prepared cookie sheet, flattening to 3/4" thickness.
* Bake until cookies are lightly browned around the edges, about 10 - 12 minutes.

Modified from Allrecipes magazine.