---
title: "Carrot Cake Muffins"
subtitle: |
  Like mini carrot cakes, so tender and delicious.
date: 2024-04-07
categories: [carrot, muffin]
editor_options:
  chunk_output_type: console
bibliography: refs.bib
---

## Ingredients

* 1 1/2 cups flour
* 1 cup white sugar
* 1/2 tsp cinnamon
* 1/2 tsp baking soda
* 1/2 tsp baking powder
* 3/4 cup vegetable oil
* 1/2 cup brown sugar
* 2 large eggs - at room temperature
* 2 tsp vanilla extract
* 2 cups finely grated carrots - not pre-shredded carrots, they should be freshly grated
  * Either the smallest holes on a box grater, or small short pieces using a hand grater.

## Instructions

* Preheat oven to 350F degrees and line a muffin tin with paper or silicone cupcake liners (or grease well with cooking spray).
* In a medium bowl whisk together **1 1/2 cups** flour, **1 cup** sugar, **1/2 tsp** cinnamon, **1/2 tsp** baking soda, and **1/2 tsp** baking powder.
* In a large bowl combine **1/2 cup** oil, **1/2 cup** brown sugar, **2** eggs, and **2 tsp** vanilla and mix well. 
* Stir in **2 cups** finely grated carrots.
* Stir dry ingredients into wet ingredients until completely incorporated.
* Fill muffin liners 2/3 full.
* Bake in preheated oven for 20-22 minutes until a toothpick inserted in the center of the muffins comes out clean. Cool for 5 minutes before transferring to a cooling rack to continue cooling.

Source: [CremeDeLaCrumb](https://www.lecremedelacrumb.com/carrot-cake-muffins/)
