---
title: "Blueberry Muffins"
subtitle: |
  Simple, one bowl blueberry muffins.
date: 2024-01-17
categories: [muffin, blueberry]
editor_options:
  chunk_output_type: console
bibliography: refs.bib
---

## Ingredients

* 1 1/2 cups (195g) all-purpose flour
* 3/4 cup (150g) white sugar
* 2 tsp baking powder
* 1/3 cup (80ml) vegetable oil
* 1 large egg
* 1/3 to 1/2 cup (80ml to 120ml) milk
* 1 1/2 tsp vanilla extract
* 6 to 8 ounces fresh or frozen blueberries, generous 1 cup

## Directions

* Preheat oven to 400 F. 
* For larger muffins, line or grease 8 muffin cups.
* For smaller muffins, line or grease 10 muffin cups.
* Whisk the **1 1/2 cups** flour, **3/4 cup** white sugar, **2 tsp** baking powder in a bowl.
* Add **1/3 cup** oil to a 1 cup measuring cup, add **1** egg to it, and then fill to the 1 cup line with milk (**1/2 to 1/3**).
* Add **1 1/2 tsp** vanilla and whisk to combine.
* Add above milk mixture to the bowl of flour and combine with a fork. Do not over mix.
* Divide into muffin tins.
* If desired, sprinkle each muffin with a little bit of white sugar.
* Bake muffins at 400 F for 15 to 20 minutes or until tops are no longer wet and a toothpick inserted into the middle of a muffin comes out with crumbs, not wet batter. 
* Transfer to a cooling rack.

Source: https://www.inspiredtaste.net/18982/our-favorite-easy-blueberry-muffin-recipe/
