---
title: "Double Chocolate Chip Cookies"
subtitle: |
  These amazing cocoa and chocolate chip cookies are delicious, and relatively easy.
date: 2023-10-17
categories: 
  - cookies
  - dessert
editor_options:
  chunk_output_type: console
---

Note that the dough should ideally chill for three hours before baking.

## Ingredients

* 1/2 cup unsalted butter, softened to room temperature
* 1/2 cup granulated white sugar
* 1/2 cup packed light or dark brown sugar
* 1 large egg, at room temperature
* 1 tsp pure vanilla extract
* 1 cup all-purpose flour
* 2/3 cup unsweetened cocoa powder
* 1 tsp baking soda
* 1 Tbsp milk
* 1 1/4 cups semi-sweet chocolate chips

## Directions

* Beat the **1/2 cup** butter, **1/2 cup** granulated white sugar, **1/2 cup** brown sugar together on medium high speed until fluffy and light in color, about 2-3 minutes. 
* Add the **1** egg and **1/2 tsp** vanilla extract, and then beat on high speed until combined. 
Scrape down the sides and bottom of the bowl as needed.
* In a separate bowl, whisk the **1 cup** flour, **2/3 cup** cocoa powder, **1 tsp** baking soda together until combined. 
* With the mixer running on low speed, slowly pour into the wet ingredients. 
* Beat on low until combined. The cookie dough will be quite thick. 
* Switch to high speed and beat in the **1 tbsp** milk, and then the **1 1/4 cup** chocolate chips. 
The cookie dough will be sticky and tacky. 
* Cover dough tightly and chill in the refrigerator for at least **3 hours** and up to **3 days**. 
**Chilling is mandatory for this sticky cookie dough.**
* Remove cookie dough from the refrigerator and allow to sit at room temperature for **10 minutes**. If the cookie dough chilled longer than 3 hours, let it sit at room temperature for about 20 minutes. This makes the chilled cookie dough easier to scoop and roll.
* Preheat oven to 350°F. Line large baking sheets with parchment paper or silicone baking mats.
* Scoop and roll dough, a heaping **1.5 tbsp** in size, into balls. To ensure a thicker cookie, make the balls taller than they are wide (almost like a cylinder or column). 
* Arrange 2-3 inches apart on the baking sheets. The cookie dough is certainly sticky, so wipe your hands clean after every few balls of dough you shape.
* Bake the cookies for 11-12 minutes or until the edges appear set and the centers still look soft. Tip: If they aren’t really spreading by minute 9, remove them from the oven and lightly bang the baking sheet on the counter 2-3x. This helps initiate that spread. Return to the oven to continue baking.
* Cool cookies for 5 minutes on the baking sheet. Transfer to a cooling rack to finish cooling.

From [Sally's Baking Recipes](https://sallysbakingaddiction.com/double-chocolate-chip-cookies-recipe/)
