---
title: "Tea Biscuits"
subtitle: |
  Simple tea biscuits. Great for a snack or breakfast.
date: 2025-04-20
categories: [biscuits, breakfast]
editor_options:
  chunk_output_type: console
---

## Ingredients

* 2 cups flour (either 1 cup all-purpose + 1 cup bread flour, or 2 cups all-purpose)
* 1 Tbsp white sugar 
* 1 Tbsp baking powder 
* 1 tsp salt
* 2 Tbsp butter
* 3 tbsp vegetable shortening
* 1 cup buttermilk or milk
* For lactose-free options, use 1/3 cup shortening instead of butter/shortening mix

## Directions 

* Preheat oven to 425°
* Place **2 cups** flour, **1 Tbsp** sugar, **1 Tbsp** baking powder, and **1 tsp** salt in large mixing bowl and stir together until mixed.
* Cut butter into small cubes; add cubed butter and shortening to the flour mixture.
* Using either a pastry blender, 2 forks, or your fingers, blend the fats into the flour until it's the consistency of wet sand.
* Pour in the buttermilk/milk and stir with a fork until the mixture forms a dough.
* Turn dough out on a floured surface and knead 2-3 times.
* Using your hands, press dough into a disc approximately 1/2" thick (I measure by the thickness of my pinky).
* Cut dough into rounds and place on a baking sheet.
* Bake at 425° for 12-15 minutes until golden brown.

Makes 8 - 10 biscuits.

Source: Amanda Cope