---
title: "Pork & Potatoes (Instant Pot)"
description: |
  Simple way to cook both meat and potatoes in the instant pot.
date: 04-11-2021
categories:
  - meat
  - pork
  - potatoes
  - main-dish
---

## Ingredients

* 2 tablespoons olive oil
* 5 (1-inch to 1 1/2-inch thick) boneless pork chops
* 1/2 teaspoon black pepper (divided)
* 1 1/2 teaspoons garlic powder (divided)
* 1 teaspoon Kosher salt
* 1 cup onion (chopped)
* 1 1/2 cups chicken broth
* 1 1/2 pounds potatoes (cut into 1 1/2-inch pieces)
* 1 1/2 teaspoons rosemary (chopped, or about 1/2 teaspoon dried chopped)
* 1 1/2 teaspoons thyme leaves (or about 1/2 teaspoon dried thyme)

## Directions

* Choose the Instant Pot sauté setting (normal) and add the olive oil. * When the pot display reads "hot," rub the chops with half of the pepper, 1/2 teaspoon of the garlic powder, and about 1/2
teaspoon of kosher salt. 
* Cook the pork chops for about 3 minutes on each side. 
* If your pork chops are large, you may have to do this in two batches. 
* Remove the chops to a plate and set aside.

* Add the **1 cup** chopped onion to the pot. 
* Cook the onion for about 2 minutes and then add **1 1/2 cups** chicken broth; stir to loosen any browned bits.

* Return chops to pot.
* Place a steaming basket or foil-lined trivet on top of the pork chops; 
* toss the potatoes with the remaining black pepper and garlic powder along with the rosemary, thyme
and 1/2 teaspoon of the kosher salt, and add potatoes on top. 
* If using a foil lined trivet, make sure you have lots of holes in the foil so the potatoes will cook.

* Secure the Instant Pot lid and make sure the valve is in the sealing position. 
* Choose pressure cook or manual (high pressure) and set the timer for 5 minutes. 
* When the time is up, let the pressure come down naturally for 10 minutes and then move the valve to the venting position to release the remaining pressure.

Modified from https://www.thespruceeats.com/instant-pot-pork-chops-and-potatoes-4780913
