---
title: "Pumpkin Cheese Cake"
subtitle: |
  Delicious cheesecake good for any time of year!
date: 2023-05-05
categories: []
editor_options:
  chunk_output_type: console
---

## Ingredients

### Crust

* 1 3/4 cups graham cracker crumbs
* 3 tbsp light brown sugar
* 1/2 tsp ground cinnamon
* 1/2 cup melted butter

### Cake

* 8oz x 3 packages cream cheese, at room temperature
* 15oz can pureed pumpkin
* 3 eggs
* 1 egg yolk
* 1/4 cup sour cream
* 1 1/2 cups white sugar
* 1/2 tsp ground cinnamon
* 1/8 tsp nutmeg
* 1/8 tsp ground cloves
* 2 tbsp all purpose flour
* 1 tsp vanilla extract

## Directions

* Preheat oven to 350F.
* Make the crust:
  * In a medium bowl, combine the **1 3/4 cups** graham cracker crumbs, **3 tbsp** light brown sugar, **1/2 tsp** ground cinnamon.
  * Add **1/2 cup** melted butter.
  * Press down flat into a 9 inch springform pan.
  * Set aside.
* Beat **8oz x 3 packages** cream cheese until smooth.
* Add **15oz** can of pumpkin puree, **3** eggs and **1** egg yolk, **1/4 cup** sour cream, **1 1/2 cup** white sugar, **1/2 tsp** ground cinnamon, **1/8 tsp** nutmeg, **1/8 tsp** ground cloves. Beat together to combine.
* Add **2 tbsp** flour and **1 tsp** vanilla extract. Beat together until well combined.
* Pour into crust and spread evenly.
* Bake at 350F for 1 hour.
* Remove from oven and let rest for 15 minutes.
* Cover with plastic wrap and refrigerate for 4 hours before serving.
