---
title: "Chili"
description: |
  Ground beef, kidney beans, tomatos and some spice!
date: 07-03-2022
categories:
  - hamburger
  - tomato
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Ingredients 

* 1 tbsp. cooking oil
* 1 tbsp minced onion, rehydrated
* 3 cloves minced garlic / 3 tsp minced garlic
* 2 tbsp. tomato paste
* 1 - 1 1/2 lb. ground beef
* 1 1/2 tbsp. chili powder
* 1 tsp. ground cumin
* 1 tsp. dried oregano
* 2 (15-oz) cans kidney beans, drained
* 2 (28-oz) can crushed tomatoes

## Toppings

* Shredded cheddar
* Sour cream
* Thinly sliced green onions

## Directions

* In a 4 quart pot over medium heat, heat **1 tbsp** oil. 
* Add **1 tbsp** minced onion and cook until soft, about 5 minutes. 
* Stir in **3 tsp** minced garlic and cook until fragrant, about 1 minute more, then add **2 tbsp** tomato paste, stirring to combine. 
* Add **1 - 1 1/2 lbs** ground beef and cook until no longer pink. Drain fat and return to heat.
* Add **1 1/2 tbsp** chili powder, **1 tsp** cumin, **1 tsp** oregano, and season generously with salt and pepper. 
* Pour in **2 cans (15 oz)** of drained and rinsed kidney beans, and **1 can (28 oz)** of crushed tomatoes and bring chili to a boil. 
* Reduce heat and simmer 20 minutes. 
* Season with more salt and pepper, if necessary

Modified 2025-04-13 to use two cans of crushed tomatoes, and a 4 quart pot.