---
title: "Mac & Cheese"
description: |
  Hearty macaroni and cheese
date: 03-20-2021
categories:
  - pasta
  - cheese
  - casserole
---

v 0.0.1

## Ingredients

* macaroni noodles - 16 ounces cooked just al-dente
* 4 Tbsp butter
* 4 Tbsp flour
* 1 1/2 cups milk
* 10 oz (by weight) freshly shredded cheddar cheese
* 1/2 tsp garlic powder
* 1/2 tsp onion powder
* Optional:
  * Cubed ham (1 cup) + 1 tsp of yellow mustard

## Instructions

* Cook 16 oz macaroni according to package directions.
* In a large saucepan, melt **4 Tbsp** butter. 
* Add **4 Tbsp** flour, mixing until all butter is in the flour and "smooth". 
* Gradually add **1 1/2 cups** milk, making sure that all of the flour/butter mix is getting mixed into the milk. 
* Heat slowly until thickened. 
* Add **1/2 tsp** garlic and onion powder.
* With heat on low, stir in **10 oz** freshly grated cheddar cheese until melted. 
* Add cheese sauce to drained macaroni.

If desired, bake in the oven at 350F for 30-45 minutes. Serve hot.

## Notes

* Don't overcook the macaroni, or this will get really, really mushy while in the oven.

**Source**: Modified from "taste of home, the Ultimate Comfort Food Cookbook", copyright 2012
