---
title: "1 Hour Cinnamon Rolls"
description: |
  A yummy treat for breakfast or a snack.
author:
  - name: Robert M Flight
    url: {}
date: 03-20-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories:
  - baked
  - roll
  - cinnamon
  - breakfast
---

## Dough 

* 1 cup milk
* 1/4 cup butter (margarine)
* 3 cups flour
* 1/2 cup flour
* 1/4 cup white sugar
* 1/2 tsp salt
* 1 egg
* 1 package rapid rise or instant yeast

* Combine **1 cup** milk and **1/4 cup** butter in a microwave-safe bowl. 
* Heat on high for 1 minute, then remove and stir.
* Continue heating in 20 second intervals, pausing after each to stir, until the butter is melted and the milk is warm to the touch but not hot.
(It should be around 110°F — I recommend measuring the temperature with a cooking thermometer.)
* If the mixture is too hot, just wait a few minutes for it to cool.

* In a separate bowl, whisk together **3 cups** flour, **1/4 cup** granulated sugar and **1/2 tsp** salt until combined.

* In the bowl of a stand mixer fitted with the dough-hook attachment, add the warm milk mixture and sprinkle the **1 package** yeast on top, then give the mixture a brief stir.  
* Add the flour mixture and **1** egg, and beat on medium-low speed until combined.
* If the dough is sticking to the sides of the bowl, add the **1/2 cup** of flour, **1/4 cup** at a time, until the dough begins to form a ball and pulls away from the sides of the bowl.
(Use no more than 3 1/2 cups of flour total.)
* Continue beating for 5 minutes on medium-low speed.
* Remove dough and form it into a ball with your hands.
* Place it in a greased bowl and cover with a damp towel.

*Let rest for 20 minutes or doubled in size.*

## Filling

* 1/4 cup packed brown sugar
* 1/4 cup white sugar
* 2 Tbsp ground cinnamon

* While the dough rests, make your filling by whisking together **1/4 cup** white sugar, **1/4 cup** brown sugar and **2 Tbsp** ground cinnamon together in a small mixing bowl until combined.

## Roll Out Dough

* 1/4 cup butter (sofened)

* Once the dough is ready, turn it out onto a floured work surface.
* Use a floured rolling pin to roll the dough out into a large rectangle, about 9 x 14 inches in size.
(If you want all of the edges to be even, you can use a pizza slicer to cut the dough into an even rectangle.)
* Use a knife or an offset spatula to spread the remaining **1/4 cup** of softened butter out evenly over the entire surface of the dough.
* Then sprinkle the dough evenly with the cinnamon and sugar mixture.

* Beginning at the 14-inch edge, tightly roll up the dough and give the final seam a little pinch so that it seals.
* Use a piece of dental floss or a knife to slice off the two ends of the roll (just 1/2-inch or so on each end, which you can discard) so that the ends are even.
* Cut the remaining dough into 11 or 12 equal pieces. (11 rolls fit well in a pie plate, whereas 12 rolls fit in a rectangular pan.)

* Place each of the cut cinnamon rolls into a greased 9-inch pie plate or 9 x 13-inch baking dish.
* Cover the dish with a damp towel, and leave it in a warm place to rise for **25 minutes**.

**Heat the oven to 350°F.**

* Once the rolls have risen, uncover the dish.
* Place on the center rack of the oven and bake for 15-20 minutes, or until the rolls are golden and cooked through.
* Remove and let cool on a wire rack for at least 5 minutes.

## Cream Cheese Icing

* 4 ounces (1/2 cup) cream cheese, softened
* 3 Tbsp butter, softened
* 1 tsp vanilla extract
* 1 1/2 cups powdered sugar
* 1–2 Tbsp milk (if needed)

Whisk ingredients together in a mixing bowl.
Drizzle on cinnamon rolls while still warm.

## Traditional Icing

* 1/4 cup butter, melted
* 1 tsp vanilla extract
* 1 1/2 cup powdered sugar
* 1–2 tablespoons milk

Whisk ingredients together in a mixing bowl.
Drizzle on cinnamon rolls while still warm.

Originally sourced from [Gimme Some Oven 1 hour Cinnamon Rolls](https://www.gimmesomeoven.com/1-hour-easy-cinnamon-rolls-recipe/)

